"""hybrid_question_source_in_session_operations

Revision ID: 02519bcc6fd4
Revises: 2cbdfb0af87c
Create Date: 2026-05-14 23:36:54.160161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02519bcc6fd4'
down_revision: Union[str, None] = '2cbdfb0af87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_operations', sa.Column('question_source', sa.String(length=50), nullable=False, server_default='bank'))
    op.add_column('session_operations', sa.Column('question_content', sa.Text(), nullable=True))
    op.add_column('session_operations', sa.Column('question_correct_answer', sa.BigInteger(), nullable=True))
    op.alter_column('session_operations', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_operations', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('session_operations', 'question_correct_answer')
    op.drop_column('session_operations', 'question_content')
    op.drop_column('session_operations', 'question_source')
    # ### end Alembic commands ###
