"""add game_sessions and session_operations tables

Revision ID: 2cbdfb0af87c
Revises: 
Create Date: 2026-05-13 00:35:43.482729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbdfb0af87c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('difficulty_params', sa.JSON(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=20), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_sessions_user_status', 'game_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('session_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('operand1', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('operand2', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('display', sa.String(length=50), nullable=False),
    sa.Column('time_limit', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('ramp_level', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('client_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_operations_session_idx', 'session_operations', ['session_id', 'question_index'], unique=False)
    op.create_index(op.f('ix_session_operations_id'), 'session_operations', ['id'], unique=False)
    op.create_index(op.f('ix_session_operations_session_id'), 'session_operations', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_operations_user_id'), 'session_operations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_operations_user_id'), table_name='session_operations')
    op.drop_index(op.f('ix_session_operations_session_id'), table_name='session_operations')
    op.drop_index(op.f('ix_session_operations_id'), table_name='session_operations')
    op.drop_index('idx_session_operations_session_idx', table_name='session_operations')
    op.drop_table('session_operations')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_index('idx_game_sessions_user_status', table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
