"""add_profile_stats_and_badges

Revision ID: 5252f1c74c5d
Revises: 02519bcc6fd4
Create Date: 2026-05-16 00:15:30.104210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5252f1c74c5d'
down_revision: Union[str, None] = '02519bcc6fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index('idx_user_badges_user_id', 'user_badges', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('elo', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_profiles', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_profiles', sa.Column('win_rate', sa.Float(), server_default='0.0', nullable=False))
    op.create_index('idx_user_profiles_elo', 'user_profiles', ['elo'], unique=False)
    op.drop_column('user_profiles', 'total_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_user_profiles_elo', table_name='user_profiles')
    op.drop_column('user_profiles', 'win_rate')
    op.drop_column('user_profiles', 'longest_streak')
    op.drop_column('user_profiles', 'current_streak')
    op.drop_column('user_profiles', 'elo')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_index('idx_user_badges_user_id', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
